name = "gamestore-tn"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[[d1_databases]]
binding = "DB"
database_name = "gamestore_db"
database_id = "8f97c9f2-8820-493a-8bec-4622d2690760"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true
